server:
    port: 9003
spring:
    rabbitmq:
        host: localhost
        port: 5672
        username: user
        password: password
        connection-timeout: 5s
    application:
        name: dispatcher-service
    config:
        import: "optional:configserver:"
    cloud:
        config:
            uri: http://localhost:8888
            request-connect-timeout: 5000
            request-read-timeout: 5000
            fail-fast: false
            retry:
                max-attempts: 6
                initial-interval: 1000
                max-interval: 2000
                multiplier: 1.1

        function:
            definition: pack|label
        stream:
            bindings:
                packlabel-in-0:
                    destination: order-accepted
                    group: ${spring.application.name}
                packlabel-out-0:
                    destination: order-dispatched
management:
    endpoints:
        web:
            exposure:
                include: bindings, env, health, heapdump, info, prometheus
    endpoint:
        health:
            show-details: always
            show-components: always
            probes:
                enabled: true
    info:
        env:
            enabled: true
        java:
            enabled: true
        os:
            enabled: true
    metrics:
        tags:
            application: ${spring.application.name}

logging:
    pattern:
        level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"